name: Build Solution on Pull Requests

on:
  pull_request:
    branches: [ master ]

jobs:
  ensure_build_on_pr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Restore WebAPI dependencies
      run: dotnet restore
    - name: Build WebAPI
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal