name: Release Docker Image On Release Published

on:
  release:
    types: [published]
    
jobs:

  publish_linux_image:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker Image
      run: docker build . --file SemanticBackup.API/Dockerfile --tag ${{secrets.DOCKER_USER}}/semanticbackupapi:latest
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/semanticbackupapi:latest
      
  publish_windows_image:

    runs-on: windows-2019
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker Image
      run: docker build . --file SemanticBackup.API/Dockerfile --tag ${{secrets.DOCKER_USER}}/semanticbackupapi:latest-windows
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/semanticbackupapi:latest-windows
