name: Docker Image CI For SemanticBackup.API-WINDOWS2019

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/semanticbackupapi:latest-windows
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/semanticbackupapi:latest-windows
