name: ghcr package publish alpha

on:
  push:
    branches: [ master ]
    
jobs:

  ghcr_package_publish_alpha:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} ghcr.io
    - name: Build the Docker Image
      run: docker build . --file SemanticBackup/Dockerfile --tag ghcr.io/${{secrets.DOCKER_USER}}/semantic-backup:latest-alpha
    - name: Docker Push
      run: docker push ghcr.io/${{secrets.DOCKER_USER}}/semantic-backup:latest-alpha
