name: ghcr package publish release

on:
  release:
    types: [published]
    
jobs:

  ghcr_package_publish_release:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} ghcr.io
    
    - name: Get Release Tag
      id: get_release_tag
      run: echo ::set-output name=TAG::${{ github.event.release.tag_name }}
    
    - name: Check if Latest Version
      id: check_latest
      run: echo ::set-output name=LATEST::${{ startsWith(github.ref, 'refs/tags/v') && github.event.release.tag_name == steps.get_release_tag.outputs.TAG }}
    
    - name: Build the versioned Docker Image
      run: docker build . --file SemanticBackup/Dockerfile --tag ghcr.io/${{secrets.DOCKER_USER}}/semantic-backup:${{ steps.get_release_tag.outputs.TAG }}
    - name: Docker Push versioned Image
      run: docker push ghcr.io/${{secrets.DOCKER_USER}}/semantic-backup:${{ steps.get_release_tag.outputs.TAG }}
    
    - name: Publish Latest Image (if applicable)
      if: steps.check_latest.outputs.LATEST == 'true'
      run: |
        docker tag ghcr.io/${{secrets.DOCKER_USER}}/semantic-backup:${{ steps.get_release_tag.outputs.TAG }} ghcr.io/${{secrets.DOCKER_USER}}/semantic-backup:latest
        docker push ghcr.io/${{secrets.DOCKER_USER}}/semantic-backup:latest
